UIIN-1402: Update to stripes v6
folio-org/ui-inventory pull request #1274
Opened 2021-01-19 17:35 UTC by mkuklis

https://issues.folio.org/browse/UIIN-1402

2021-01-19 19:21 UTC, Baroquem approved these changes

2021-01-20 09:42 UTC, SergiyVSergiyenko approved these changes

2021-01-20 17:11 UTC, zburke requested changes
With react 16 in place, the Jest and BigTest tests pass for me.

2021-01-20 17:11 UTC, zburke commented on package.json
> +    "react-dom": "^17.0.1",
Nope, not now. Eventually, yes, but react 17 is STRIPES-722 and that's separate from STRIPES-721.

2021-01-20 18:30 UTC, zburke approved these changes
LGTM, and tests pass now too!

2021-01-20 18:51 UTC, merged