UIIN-1639: Make mapped fields read-only for MARC holdings records
folio-org/ui-inventory pull request #1468
Opened 2021-09-28 14:34 UTC by Vladyslav-Velytskyi

# UIIN-1639: Edit FOLIO Inventory Holdings record > When Source = MARC > Then make mapped fields read-only

## Purpose
Add `disabled` attribute for necessary fields.

Issue: [UIIN-1639](https://issues.folio.org/browse/UIIN-1639)

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2021-10-01 13:25 UTC, BogdanDenis approved these changes

2021-10-01 13:52 UTC, mariiaschv approved these changes

2021-10-04 18:56 UTC, mkuklis approved these changes

2021-10-04 18:56 UTC, mkuklis commented on src/edit/electronicAccessFields.js
> +  isMARCRecord: PropTypes.bool,
@Vladyslav-Velytskyi could we use `canEdit` for this instead of introducing a new prop?

2021-10-04 20:12 UTC, zburke requested changes
MARC-ness and editability happen to overlap here, but they are not the same. As @mkuklis suggested, instead of checking `isMARCRecord` everywhere, use `isMARCRecord` to set `canEdit` and trigger `disabled` based on `canEdit` alone. I know it seems petty, but having centralized logic will be really nice for the next time when we only have to change 
```
isEditable = canEdit && !isMARCRecord && !hasOtherReadOnlyCondition;
```
in one place.

2021-10-05 12:13 UTC, Vladyslav-Velytskyi commented on src/edit/electronicAccessFields.js
> +  isMARCRecord: PropTypes.bool,
Thank you, nice suggestion. But here is one problem, `RepeatableField` has prop `canEdit` which doesn't work. It is thrown directly into a `FieldArray` that does not support `canEdit` prop. Ыo it was necessary to add support for this prop in `RepeatableField`. By the way, it looks better then with `isMARCSource`

2021-10-07 08:35 UTC, merged