UIIN-1746: Create Jest/RTL test for HoldingButtonsGroup
folio-org/ui-inventory pull request #1728
Opened 2022-06-29 08:14 UTC by Svitlana-Korol

## Description
Created Jest/RTL test for HoldingButtonsGroup

## Issues
[UIIN-1673](https://issues.folio.org/browse/UIIN-1673)

## Screenshots
![image](https://user-images.githubusercontent.com/96055497/176386640-45f352ce-6fe2-4b5c-a086-0b647a68e94d.png)

2022-06-29 11:08 UTC, BogdanDenis requested changes

2022-06-29 11:08 UTC, BogdanDenis commented on src/Instance/HoldingsList/Holding/HoldingButtonsGroup.test.js
> +    expect(getByRole('button', { name:  'View holdings' })).toBeDefined();
Please also add tests that check that clicking on these buttons calls callbacks

2022-06-29 14:32 UTC, BogdanDenis approved these changes

2022-06-30 14:16 UTC, mariiaschv approved these changes

2022-07-04 07:31 UTC, merged