UIIN-1690: Jest/RTL Tests for validation.js
folio-org/ui-inventory pull request #1915
Opened 2022-12-23 08:01 UTC by VSnehalatha

Jest/RTL test for validation.js
Refs: [UIIN-1690](https://issues.folio.org/browse/UIIN-1690)

2022-12-23 08:22 UTC, cchitneedi approved these changes

2022-12-23 10:53 UTC, KetineniM approved these changes

2022-12-23 14:02 UTC, ssandupatla approved these changes

2022-12-27 22:38 UTC, zburke requested changes
Please test both functions with valid and invalid data. Right now, validateSubInstances is only tested with invalid data.

2022-12-27 22:38 UTC, zburke commented on src/validation.test.js
> +  });
This is a great start! Please test `validateSubInstances` for success the same way you did for `validateTitles`.

2022-12-29 20:14 UTC, zburke approved these changes
Nice work!

2022-12-29 20:52 UTC, merged