UIIN-2310: Bump quick-marc to 6.0.0
folio-org/ui-inventory pull request #1954
Opened 2023-01-26 11:20 UTC by Dmytro-Melnyshyn

## Purpose
Bump quick-marc to 6.0.0

## Issues
[UIIN-2310](https://issues.folio.org/browse/UIIN-2310)

## Approach

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-01-26 11:59 UTC, BogdanDenis approved these changes

2023-01-26 22:53 UTC, vashjs approved these changes

2023-01-27 12:27 UTC, zburke requested changes
CHANGELOG says 10.0.0 but package.json says 9.3.0. Which is it? By itself, this is not a breaking change since quick-marc is a private, direct-dep.

2023-01-27 12:55 UTC, Dmytro-Melnyshyn commented
> CHANGELOG says 10.0.0 but package.json says 9.3.0. Which is it? By itself, this is not a breaking change since quick-marc is a private, direct-dep.

@zburke thanks, I've fixed it.

2023-01-27 13:32 UTC, zburke approved these changes
LGTM

2023-01-27 13:34 UTC, merged