UIIN-1793 Create JEST/RTL tests for InstanceIdentifiersView.js
folio-org/ui-inventory pull request #2042
Opened 2023-03-10 08:07 UTC by VSnehalatha

Create JEST/RTL tests for InstanceIdentifiersView.js
REFS: [UIIN-1793](https://issues.folio.org/browse/UIIN-1793)

2023-03-10 09:21 UTC, cchitneedi approved these changes

2023-03-17 06:52 UTC, ssandupatla approved these changes

2023-03-20 03:18 UTC, zburke requested changes
This is mostly a test of how MCL handles an empty list. 

Please add a second `it` clause that renders `<InstanceIdentifiersView>` with non-empty arrays in `identifiers` and `identifierTypes`.

2023-03-28 20:51 UTC, ryandberger approved these changes

2023-03-29 10:41 UTC, merged