UIIN-1750 Create JEST/RTL tests for FastAddForm.js
folio-org/ui-inventory pull request #2057
Opened 2023-03-16 14:16 UTC by VSnehalatha

Create Jest/RTL test for src/settings/FastAdd/FastAddForm.js
Refs: https://issues.folio.org/browse/UIIN-1750

2023-03-17 10:19 UTC, cchitneedi approved these changes

2023-03-22 17:38 UTC, ryandberger commented on src/settings/FastAdd/FastAddForm.test.js
> +  test('Cancel button shoul be truthy', async () => {
Spelling mistake: `should`. Also on line 57.

2023-03-22 17:39 UTC, ryandberger requested changes
Fix test names. Looks good otherwise.

2023-03-23 19:21 UTC, ryandberger approved these changes

2023-03-24 04:08 UTC, merged