UIIN-2433  Inventory: Retain Search/Browse query/options/filter and facet selections UNLESS user resets/clear selections
folio-org/ui-inventory pull request #2177
Opened 2023-06-14 10:57 UTC by BogdanDenis

## Description
Retain Search/Browse query/options/filter and facet selections UNLESS user resets/clear selections
Store last search mode in `LastSearchTermsProvider` context

## Screenshots

## Issues
[UIIN-2433](https://issues.folio.org/browse/UIIN-2433)

2023-06-21 11:01 UTC, BogdanDenis commented
@folio-org/fe-tl-reviewers please take a look

2023-06-22 09:38 UTC, Terala-Priyanka reviewed
Looks like there are some probably linting errors listed in "Unchanged files with check annotations". If possible could you fix them?

2023-06-22 09:38 UTC, Terala-Priyanka commented on src/components/FilterNavigation/FilterNavigation.js
> +          const sort = segmentsSortBy.find(x => x.name === name).sort || '';
Looks like this declaration is no more used. Could you reevaluate the need?

2023-06-22 09:38 UTC, Terala-Priyanka commented on src/components/InstancesList/InstancesList.js
> +      pathname: PropTypes.string,
Could you check if it is possible to further increase the coverage on this file?

2023-06-23 00:28 UTC, Terala-Priyanka approved these changes

2023-06-23 00:28 UTC, Terala-Priyanka commented on src/components/FilterNavigation/FilterNavigation.js
> +}
Could you fix linting error here by adding semi colon?

2023-06-23 09:04 UTC, Dmytro-Melnyshyn requested changes

2023-06-23 09:04 UTC, Dmytro-Melnyshyn commented on src/components/SearchModeNavigation/SearchModeNavigation.test.js
> +  useHistory,
Please remove it, it is not used anywhere.

2023-06-23 09:46 UTC, Dmytro-Melnyshyn commented on src/providers/LastSearchTermsProvider.js
> +    setItem(`${namespace}/search.segment`, null);
It is also necessary to reset all search terms for each segment in `resetStorageAfterLogout` to not have them after login.

2023-06-23 12:21 UTC, Dmytro-Melnyshyn requested changes

2023-06-23 12:21 UTC, Dmytro-Melnyshyn commented on src/components/SearchModeNavigation/SearchModeNavigation.js
> +      pathname: searchModeRoutesMap[segment],
Please look at the scenario described above.

2023-06-23 14:46 UTC, Dmytro-Melnyshyn approved these changes

2023-06-27 11:08 UTC, merged