UIIN-1920 Implement Advanced Search modal
folio-org/ui-inventory pull request #2197
Opened 2023-07-05 11:56 UTC by BogdanDenis

## Description

## Screenshots

## Issues

## Related PRs

2023-07-11 08:25 UTC, mariia-aloshyna approved these changes
Wow, it's a kinda cool feature! LGTM

2023-07-11 13:34 UTC, Dmytro-Melnyshyn requested changes

2023-07-11 13:34 UTC, Dmytro-Melnyshyn commented on src/utils.js
> +  }
It looks like it's redundant.

2023-07-11 13:34 UTC, Dmytro-Melnyshyn commented on src/utils.js
> +export function buildAdvancedSearchQuery(queryParams, pathComponents, resourceData, logger, props) {
Can we utilize the `buildQuery` function from the `builtManifestObject.js` file? By simply adding an `if (queryIndex === AdvancedSearch)` condition?

2023-07-11 13:34 UTC, Dmytro-Melnyshyn commented
1. Seems the `Query` search option should be excluded from the advanced search.
2. `Contans all` is changed to `Exact phrase` after the second opening of the advanced search modal.
3. The request comprises escapes that lead to incorrect results number `(keyword==/string \"a\" or title all \"b\") sortby title`.
4. [Page falls](https://github.com/folio-org/ui-inventory/assets/77053927/4f802011-d416-4151-88b7-e8a33f0e74f0)
5. Page falls with the same error if I select the `Advanced search` search option and paste `(keyword==/string "a" or title all "b") sortby title`.

2023-07-11 18:21 UTC, Dmytro-Melnyshyn commented
> 2. I haven't found a solution how to get used match option 100% of the time. It's difficult because match option is not a single symbol, but a combination of `==`, `==/string`, `all` etc and prefix or postfix `*` symbol
> 3. I think that's the correct format according to docs https://github.com/folio-org/mod-search#cql-query-modifiers

2. Have you tried the solution from this [Spike](https://wiki.folio.org/pages/viewpage.action?pageId=118265036)?
3. When quotes are escaped, they are treated as user input. I think the request query should be `(keyword all "a" and oclc="*b*") sortby title` instead of `(keyword all \"a\" and oclc=\"*b*\") sortby title`.

2023-07-12 10:00 UTC, Dmytro-Melnyshyn requested changes

2023-07-12 10:00 UTC, Dmytro-Melnyshyn commented on src/utils.js
> +import { makeQueryFunction } from '@folio/stripes/smart-components';
Please fix eslint warnings in this file.

2023-07-13 07:43 UTC, Dmytro-Melnyshyn commented
[Page crashes](https://github.com/folio-org/ui-inventory/assets/77053927/4b75c29a-271a-48cb-a7d7-9328129b820e)

2023-07-14 11:20 UTC, merged