UIIN-2518: Make the Move actions available regardless of how user navigated to the record.
folio-org/ui-inventory pull request #2262
Opened 2023-09-13 10:11 UTC by Dmytro-Melnyshyn

## Purpose
Make the Move actions available regardless of how user navigated to the record.

## Issue
[UIIN-2518](https://issues.folio.org/browse/UIIN-2518)

## Screencast

https://github.com/folio-org/ui-inventory/assets/77053927/1a6e9f98-0aca-46f3-81c0-fd6a3758bd2a

## Approach

## Refs

## Screenshots

2023-09-13 11:13 UTC, mariia-aloshyna approved these changes

2023-09-13 13:08 UTC, BogdanDenis requested changes

2023-09-13 13:08 UTC, BogdanDenis commented on src/ViewInstance.js
> -            {!openedFromBrowse && (
I think we can remove all uses of `openedFromBrowse` - one more place is in `showInventoryMenuSection` variable and there rest

2023-09-14 08:28 UTC, BogdanDenis approved these changes

2023-09-14 08:30 UTC, merged