UIIN-2600: Remove error message after switch from Instance Edit screen to another app
folio-org/ui-inventory pull request #2311
Opened 2023-10-17 11:05 UTC by OleksandrHladchenko1

## Purpose

* Remove error message "Something went wrong" after switch from Instance Edit screen to another app

## Approach

* Added optional chaining for instance form values

## Refs

[UIIN-2600](https://issues.folio.org/browse/UIIN-2600)

## Screenshots

https://github.com/folio-org/ui-inventory/assets/85172747/19f09e3e-a38b-46a2-a88b-b33bb1e78912

2023-10-17 12:11 UTC, zburke requested changes
We went from not enough null-checking to too much. Let's pick either ternary or optional chaining. It doesn't matter which but we don't need both.

2023-10-17 12:11 UTC, zburke commented on src/edit/InstanceForm.js
> +    const instanceTypeOptions = referenceTables.instanceTypes ? referenceTables.instanceTypes?.map(
Pick one: we don't need both a ternary and optional chaining here.

2023-10-17 12:11 UTC, zburke commented on src/edit/InstanceForm.js
> +      ?.map(
Ah, now I see what happened above: here, there was no ternary and you solved the bug with optional chaining, and so added optional chaining everywhere. It doesn't matter which we choose, but let's pick one pattern and stick with it.

2023-10-19 09:33 UTC, mariia-aloshyna approved these changes

2023-10-19 10:35 UTC, BogdanDenis approved these changes

2023-10-19 13:38 UTC, merged