UIIN-2686: "Saving instance failed" modal does not show error message
folio-org/ui-inventory pull request #2352
Opened 2023-11-21 13:59 UTC by mariia-aloshyna

## Purpose

When there is an error while saving the edited instance, the confirmation modal shows "undefined" instead of an error message.

## Approach

- To parse error correctly

## Refs

https://issues.folio.org/browse/UIIN-2686

## Screenshots

<img width="614" alt="Screenshot 2023-11-21 at 15 58 03" src="https://github.com/folio-org/ui-inventory/assets/55138456/be2287e9-8106-401f-9568-da2bfe0a89d1">

2023-11-21 14:32 UTC, BogdanDenis requested changes

2023-11-21 14:32 UTC, BogdanDenis commented on src/Instance/InstanceEdit/InstanceEdit.js
> +      <div style={{ overflowWrap: "break-word", hyphens: "auto" }}>
Please add a new class to css file

2023-11-22 12:32 UTC, mariia-aloshyna commented on src/Instance/InstanceEdit/InstanceEdit.js
> +      <div style={{ overflowWrap: "break-word", hyphens: "auto" }}>
Done

2023-11-22 13:57 UTC, Dmytro-Melnyshyn approved these changes

2023-11-22 13:57 UTC, Dmytro-Melnyshyn commented on src/Instance/InstanceEdit/InstanceEdit.js
> +    }
Please fix eslint warnings

2023-11-23 22:32 UTC, merged