Release v10.0.9
folio-org/ui-inventory pull request #2379
Opened 2023-12-29 11:27 UTC by BogdanDenis

2023-12-29 15:47 UTC, mariia-aloshyna approved these changes

2023-12-29 15:47 UTC, mariia-aloshyna requested changes

2023-12-29 15:47 UTC, mariia-aloshyna commented on CHANGELOG.md
> +## [10.0.9](https://github.com/folio-org/ui-inventory/tree/v10.0.8) (2023-12-29)
```suggestion
## [10.0.9](https://github.com/folio-org/ui-inventory/tree/v10.0.9) (2023-12-29)
```

2024-01-02 10:25 UTC, Dmytro-Melnyshyn approved these changes

2024-01-02 11:40 UTC, mariia-aloshyna approved these changes

2024-01-02 11:45 UTC, merged