UIIN-2754: Add the ability to update ownership of items
folio-org/ui-inventory pull request #2582
Opened 2024-09-05 09:25 UTC by OleksandrHladchenko1

## Purpose

 * Be able to move items from one FOLIO tenant to another

## Approach

* Display **Update ownership** button for user with multiple affiliations for Item linked to Shared Instance and when user has **Inventory: Update ownership** permission.
* Transformed `ItemView` component into the functional one in order to use hooks such as `useHoldingMutation` and `useUpdateOwnership`
* Added `tenant` parameter to `useHoldingMutation` hook in order to have the ability to create holding for another tenant.
* Added `UpdateItemOwnershipModal` component that contains two fields: `Selection` component with affiliations (except current and central one) and `FieldHolding` component that allows us to choose holding for the chosen tenant OR create a new holding, based on the location.
* Added `path` parameter to `useUpdateOwnership` hook in order to use it for updating ownership of both holdings and items.
* Added unit tests

## Refs

[UIIN-2754](https://folio-org.atlassian.net/browse/UIIN-2754)

## Screenshots

https://github.com/user-attachments/assets/e98610a2-4235-40f2-adab-f6e1a87a6fe0

2024-09-05 09:34 UTC, BogdanDenis requested changes
Please increase code coverage to 80%, especially for ItemView component because it has a lot of changes

2024-09-05 14:43 UTC, mariia-aloshyna commented on src/components/UpdateItemOwnershipModal/UpdateItemOwnershipModal.js
> +                  placeholder="Select affiliation"
let's make it translatable

2024-09-05 14:43 UTC, mariia-aloshyna commented on src/components/UpdateItemOwnershipModal/UpdateItemOwnershipModal.test.js
> +describe('UpdateItemOwnershipModal', () => {
add test for axe, please

2024-09-09 12:42 UTC, OleksandrHladchenko1 commented
> Please increase code coverage to 80%, especially for ItemView component because it has a lot of changes

Hi @BogdanDenis I increased test coverage for ItemView component. Please review this PR one more time.
![image](https://github.com/user-attachments/assets/17b47220-4bdc-4dba-ba21-37d0862795f4)

2024-09-09 12:48 UTC, BogdanDenis requested changes

2024-09-09 12:48 UTC, BogdanDenis commented on src/views/ItemView.js
> +          aria-label={`Instance HRID - ${x.briefInstance?.id}`}
Please add this to translations

2024-09-09 13:00 UTC, OleksandrHladchenko1 commented on src/views/ItemView.js
> +          aria-label={`Instance HRID - ${x.briefInstance?.id}`}
Done!

2024-09-09 14:21 UTC, mariia-aloshyna commented on src/views/ItemView.js
> +                })}
I would suggest moving this and the ones below to a variable and using `useMemo` so as not to re-render values each time.

2024-09-09 14:21 UTC, mariia-aloshyna commented on src/views/ItemView.js
> +    identifier: get(item, 'itemIdentifier', '-'),
use `NoValue` instead of `-`

2024-09-09 14:21 UTC, mariia-aloshyna commented on src/views/ItemView.js
> +            style={wrappingCell}
can `TextLink` be used here?

2024-09-09 16:17 UTC, mariia-aloshyna approved these changes

2024-09-10 06:26 UTC, merged