UIIN-3116: Add call number browse settings.
folio-org/ui-inventory pull request #2694
Opened 2024-12-12 18:45 UTC by Dmytro-Melnyshyn

## Description
Create new settings for call number type sorting.

## Approach

## Refs
[UIIN-3116](https://folio-org.atlassian.net/browse/UIIN-3116)

## Screenshots

https://github.com/user-attachments/assets/d6fba09a-e3d9-4c04-864d-31636770b37d

2024-12-13 14:13 UTC, mariia-aloshyna approved these changes

2024-12-16 10:29 UTC, BogdanDenis requested changes

2024-12-16 10:29 UTC, BogdanDenis commented on package.json
> +        "permissionName": "ui-inventory.settings.call-number-browse",
Please add a translation for a new permission

2024-12-17 11:15 UTC, BogdanDenis approved these changes

2024-12-17 11:15 UTC, merged