UIIN-3106: Add 'linked-data' interface to 'optionalOkapiInterfaces'
folio-org/ui-inventory pull request #2702
Opened 2024-12-18 16:46 UTC by pkjacob

## Purpose
Inventory UI makes API call to the following API in linked-data module
[GET linked-data/inventory-instance/:{id}/import-supported](https://github.com/folio-org/mod-linked-data/blob/master/descriptors/ModuleDescriptor-template.json#L95)

Per [stripes documentation](https://github.com/folio-org/stripes/blob/8790eaaccc2fa58f5500570f5bdc6a47c7a53ff3/doc/dev-guide.md), the optional interfaces that UI module uses should be declared in `optionalOkapiInterfaces section of package.json` file. 

Purpose of this ticket is to update `optionalOkapiInterfaces` section of the package.json with the following
`"linked-data": "1.0"`

2024-12-18 17:30 UTC, zburke approved these changes
LGTM, though it's worth noting that the function leveraging this endpoint in [ViewInstance.js](https://github.com/folio-org/ui-inventory/blob/42c945284b28fae72300ab144f303a64253161e7/src/ViewInstance.js#L323-L344) is missing `<IfInterface>` protection, so it's nice that you're adding this declaration in `package.json` to include it in the module descriptor, but practically speaking the access is still unchecked and this is effectively a required interface.

2024-12-19 10:58 UTC, BogdanDenis requested changes
Please add an entry in CHANGELOG

2024-12-19 19:15 UTC, pkjacob commented
@BogdanDenis  Change log added.

2024-12-20 12:56 UTC, BogdanDenis approved these changes

2024-12-26 12:56 UTC, merged